gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - '#179299'
      - bold
    inactiveBorderColor:
      - '#6c6f85'
    optionsTextColor:
      - '#1e66f5'
    selectedLineBgColor:
      - '#ccd0da'
    cherryPickedCommitBgColor:
      - '#bcc0cc'
    cherryPickedCommitFgColor:
      - '#179299'
    unstagedChangesColor:
      - '#d20f39'
    defaultFgColor:
      - '#4c4f69'
    searchingActiveBorderColor:
      - '#df8e1d'

  authorColors:
    '*': '#7287fd'

git:
  paging:
    colorArg: always
    useConfig: false
    pager: delta --paging=never
  commitPrefix:
    - pattern: "^[^/]+\\/([A-Z]+-\\d+).*"
      replace: '$1 '

os:
  editCommand: "nvim"
  openCommand: open {{filename}}
  openLinkCommand: open {{link}}

services:
  gitlab.skillbox.pro: gitlab:gitlab.skillbox.pro

customCommands:
  - key: "G"
    context: "global"
    description: "Push and create MR to target branch (default dev)"
    prompts:
      - type: "input"
        title: "Branch to create MR against"
        initialValue: "dev"
    command: "uv run git pushbackbranch {{index .PromptResponses 0}}"
